### PR TITLE
Allow arbitrary service environment variables

### LINKED ISSUE #67: Enhancement: Support ADMIN_USERNAME and ADMIN_PASS role variables
https://rocket.chat/docs/administrator-guides/create-the-first-admin/
It would be very useful to be able to create the admin account during deployment.

### PR DESCRIPTION
**Pull request by xenithorb**
- New var: `rocket_chat_service_environment`:
    - This is designed to be a dict, so for every key value pair
      will appear a new line in the rocketchat.service file to
      be exported to the environment of the nodejs process.

 - Closes #67

### CODE REVIEW

**Comment by xenithorb** [comment]
This would also allow for injecting service environment variables from the commandline too via the `ansible-playbook -e` flag.

**Comment by xenithorb** [comment]
### CAUTION: Special attention needs to be given to quoting the original value data.

Since this is not well tested. Perhaps later one we'll need to `| quote` the variable or `regex_replace`.........

**Comment by nickbroon** [comment]
I'd guess for completeness this should probably also be added to rocketchat_upstart.j2 template for the case of images that use upstart instead of systemd, which I think is the case for Ubuntu Trusty.

**Comment by xenithorb** [comment]
Ultimately you're right, though I'm wanting to drop Ubuntu 14 soonish. The hassle it brings to the role is unlike any other distro at the current moment.

**Comment by nickbroon** [comment]
I wouldn't mind if you dropped Ubuntu Trusty support.

**Comment by nickbroon** [comment]
I've just tested this, and it appears to work for my use case. It will be great to able to bring up a Rocket.Chat server already configured using Ansible.
Do you plan to merge this to the master branch and release it?
I'd agree that long term quoting is probably a good idea.

**Comment by xenithorb** [comment]
Soonish, I'm working on the last set of updates for mongodb and other stuff, and then vagrant testing all the distros before I release to master.

**Pull request merged**
