### PR TITLE
Small changes to get the role working on centos/7

### PR DESCRIPTION
**Pull request by iptizer**

### CODE REVIEW

**Comment by xenithorb** [comment]
What is it in the '@Development Tools' group that you're specifically targeting? I'd much rather just add a few packages if you think they're missing, but I regularly test this and use it against CentOS and Fedora myself, so I'm not sure what the problem is for you?

**Comment by iptizer** [comment]
Hi, I used the Vagrantbox Centos/7 for testing. It seemed that npm was trying to compile some packages using gcc or g++ and various other tools.
I think the relevant error is as follows:
```
TASK [RocketChat.Server : Install Rocket.Chat via NPM]  rocketchat.retry rocketchat.yml  fatal: [xxx.de]: FAILED! => {"changed": false, "cmd": "/usr/bin/npm install", "failed": true, "msg": "node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@6.10.1 (node-v48 ABI) (falling back to source compile with node-gyp)
make:********@0.0.0 install script 'node npm-rebuild.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node npm-rebuild.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /var/lib/rocket.chat/bundle/programs/server/npm-debug.log", "rc": 1, "stderr": "node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@6.10.1 (node-v48 ABI) (falling back to source compile with node-gyp)
make: g++: Command not found
make: rocketchat.retry rocketchat.yml [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
```

Beforehand I wasn't digging so deep. It seems that bcrypt library download fails, a fallback to compile the sources is made, which fails due to missing "@Development Tools".

I'm not quite sure where this wrong dl url comes from and how to fix this. Doesn't seem like its hardcoded in the ansible-role.

**Comment by iptizer** [comment]
BTW, we could remove @Development Tools after the installation is complete.

**Comment by jlozadad** [comment]
do you need all the rpms in development tools or just a handful?

**Comment by xenithorb** [comment]
I _really_ don't think this is necessary. Are you doing something specific in your implementation of this role that it needs to build things?

I just did a vagrant test with the official centos 7 image and it works.... 

I'm not the "works for me" type, but this seems off, so to continue you need to provide additional information or close/recant this proposal

**Comment by instantchow** [comment]
I concur with the needing the commits for my CentOS 7 image. @xenithorb  are you using a CentOS minimal image? 

Also, perhaps related I needed to update openssl to get past a npm NodeJS install see #62 

Perhaps a "clean run" of the playbook works and one with a bunch of playbook re-runs due to failures caused something to need a rebuild of something npm?

**Comment by xenithorb** [comment]
I still do not believe `development-tools` group is necessary, anymore. Please double check with the most recent versions of `master` and `develop`.

Please open an issue or another PR with suggestions if you're still having this issue.

**Pull request closed without merging**
